### ISSUE TITLE
无法更新依赖包

### ISSUE THREAD

**Issue by manuchen** [leancloud/StorageStarted#6]
// LeanCloud 基础包
    compile 'cn.leancloud.android:avoscloud-sdk:v3.+'
    compile 'cn.leancloud.android:avoscloud-statistics:v3.+'

更新不下来。

**Comment by daweibayu** [comment]
你在试一下？这边看是可以正常访问的，http://mvn.leancloud.cn/nexus/content/repositories/public/cn/leancloud/android/avoscloud-sdk/v3.14.10/

**Comment by manuchen** [comment]
重新搭建了android studio 可以使用

**Comment by luffykou** [comment]
导包：
    implementation 'cn.leancloud:storage-android:8.2.0'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

文档示例代码中类库找不到AVUser\AVFriendshipRequest等的，把类名中的AV替换为LC尝试
